Remade using messages from gen.py
tryalab/av20tr-canbus pull request #36
Opened 2021-11-17 13:52 UTC by JohannesAhlstrom

Since "datax = data" follows data, i.e. seems to have been a pointer-copy of data, I could not use it.
data is disasembled in generate.py, so I rewrote signals slightly to use messages.

2021-11-17 18:36 UTC, Merculafil approved these changes

2021-11-17 18:36 UTC, Merculafil commented on generators/signals.py
> +    print(textfile)
Vi bör inte ha print här i slutet

2021-11-17 18:37 UTC, Merculafil requested changes

2021-11-17 18:37 UTC, Merculafil commented on generators/signals.py
> +    print(textfile)
Vi bör inte ha print här i slutet

2021-11-17 18:52 UTC, JohannesAhlstrom commented on generators/signals.py
> +    print(textfile)
Fixat

2021-11-18 09:12 UTC, Merculafil approved these changes

2021-11-18 09:13 UTC, merged